const clean=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const number=v=>{const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const pair=v=>{const m=String(v??'').match(/(\d+)\s*[-/]\s*(\d+)/);return m?[+m[1],+m[2]]:[null,null]};
const add=(o,k,v)=>{if(Number.isFinite(v))o[k]=(o[k]??0)+v};
const assign=(o,k,v)=>{if(Number.isFinite(v))o[k]=+v.toFixed(4)};
const ratio=(a,b,s=100)=>Number.isFinite(a)&&Number.isFinite(b)&&b>0?a/b*s:null;
const statMap=row=>Object.fromEntries((row?.statistics??[]).map(x=>[clean(x.name||x.label),x.displayValue??x.value]));
const first=(o,...keys)=>{for(const k of keys)if(Number.isFinite(o[k]))return o[k];return 0};

export function normalizeBasketball({season,teams,games,summaries=[],warnings=[]}){
  const output={season,updatedAt:new Date().toISOString(),sources:{espn:true},warnings,teams:{},games,venues:{}},totals={};
  for(const t of teams){output.teams[t.name]={id:t.id,name:t.name,aliases:[t.abbr].filter(Boolean),conference:t.conference,gamesPlayed:0,dataWeight:0,power:0,hca:3.2,raw:{},model:{}};totals[t.name]={g:0,p:0,pa:0,hw:0,hg:0,rw:0,rg:0,nw:0,ng:0,o:{},d:{}}}
  for(const game of games.filter(g=>g.completed&&Number.isFinite(g.homePoints)&&Number.isFinite(g.awayPoints)))for(const [name,isHome,p,pa] of [[game.homeTeam,true,game.homePoints,game.awayPoints],[game.awayTeam,false,game.awayPoints,game.homePoints]]){const t=totals[name];if(!t)continue;t.g++;t.p+=p;t.pa+=pa;if(game.neutralSite){t.ng++;if(p>pa)t.nw++}else if(isHome){t.hg++;if(p>pa)t.hw++}else{t.rg++;if(p>pa)t.rw++}}
  for(const summary of summaries){const rows=summary?.boxscore?.teams??[];if(rows.length<2)continue;for(const row of rows){const t=totals[row.team?.displayName],opp=rows.find(x=>x!==row);if(!t)continue;for(const [bucket,map] of [[t.o,statMap(row)],[t.d,statMap(opp)]])for(const [k,v] of Object.entries(map)){const n=number(v);if(n!==null)add(bucket,k,n);const [a,b]=pair(v);if(a!==null){add(bucket,k+'made',a);add(bucket,k+'attempts',b)}}}}
  const diffs=[];
  for(const team of teams){const out=output.teams[team.name],t=totals[team.name],g=t.g,m=out.model,o=t.o,d=t.d;if(!g)continue;out.gamesPlayed=g;out.dataWeight=+(g/(g+5)).toFixed(4);assign(m,'ppg',t.p/g);assign(m,'pointsAllowed',t.pa/g);assign(m,'pointDiff',(t.p-t.pa)/g);assign(m,'homeRecordPct',ratio(t.hw,t.hg));assign(m,'roadRecordPct',ratio(t.rw,t.rg));assign(m,'neutralRecordPct',ratio(t.nw,t.ng));
    const fgm=first(o,'fieldgoalsmade','fieldgoalsmademade'),fga=first(o,'fieldgoalsattempted','fieldgoalsmadeattempts','fieldgoalsattempts'),tpm=first(o,'threepointfieldgoalsmade','threepointfieldgoalsmademade'),tpa=first(o,'threepointfieldgoalsattempted','threepointfieldgoalsmadeattempts','threepointfieldgoalsattempts'),ftm=first(o,'freethrowsmade','freethrowsmademade'),fta=first(o,'freethrowsattempted','freethrowsmadeattempts','freethrowsattempts'),orb=first(o,'offensiverebounds'),drb=first(o,'defensiverebounds'),to=first(o,'turnovers'),ast=first(o,'assists');
    const ofgm=first(d,'fieldgoalsmade','fieldgoalsmademade'),ofga=first(d,'fieldgoalsattempted','fieldgoalsmadeattempts','fieldgoalsattempts'),otpm=first(d,'threepointfieldgoalsmade','threepointfieldgoalsmademade'),otpa=first(d,'threepointfieldgoalsattempted','threepointfieldgoalsmadeattempts','threepointfieldgoalsattempts'),ofta=first(d,'freethrowsattempted','freethrowsmadeattempts','freethrowsattempts'),oorb=first(d,'offensiverebounds'),oto=first(d,'turnovers');
    const poss=fga-orb+to+.475*fta,oposs=ofga-oorb+oto+.475*ofta,avgPoss=(poss+oposs)/2;
    assign(m,'possessions',avgPoss/g);assign(m,'tempo',avgPoss/g);assign(m,'offEff',t.p/poss*100);assign(m,'defEff',t.pa/oposs*100);assign(m,'netEff',t.p/poss*100-t.pa/oposs*100);assign(m,'fgPct',ratio(fgm,fga));assign(m,'efgPct',ratio(fgm+.5*tpm,fga));assign(m,'twoPct',ratio(fgm-tpm,fga-tpa));assign(m,'threePct',ratio(tpm,tpa));assign(m,'threeRate',ratio(tpa,fga));assign(m,'ftPct',ratio(ftm,fta));assign(m,'ftRate',ratio(fta,fga,1));assign(m,'assistRate',ratio(ast,fgm));assign(m,'assistTurnover',ratio(ast,to,1));assign(m,'turnoverRate',ratio(to,poss));assign(m,'offReboundPct',ratio(orb,orb+first(d,'defensiverebounds')));assign(m,'defReboundPct',ratio(drb,drb+oorb));assign(m,'oppFgPct',ratio(ofgm,ofga));assign(m,'oppEfgPct',ratio(ofgm+.5*otpm,ofga));assign(m,'oppThreePct',ratio(otpm,otpa));assign(m,'oppFtRate',ratio(ofta,ofga,1));assign(m,'forcedTurnoverRate',ratio(oto,oposs));assign(m,'stealsGame',first(o,'steals')/g);assign(m,'blocksGame',first(o,'blocks')/g);assign(m,'foulsGame',first(o,'fouls','personalFouls')/g);assign(m,'reboundMargin',(orb+drb-first(d,'offensiverebounds')-first(d,'defensiverebounds'))/g);assign(m,'pointsPossession',t.p/poss);assign(m,'oppPointsPossession',t.pa/oposs);assign(m,'trueShooting',ratio(t.p,2*(fga+.44*fta)));assign(m,'oppTrueShooting',ratio(t.pa,2*(ofga+.44*ofta)));assign(m,'ftAttempts',fta/g);assign(m,'ftPossessionRate',ratio(fta/2,poss));assign(m,'foulsDrawn',first(d,'fouls','personalfouls')/g);assign(m,'foulDifferential',(first(d,'fouls','personalfouls')-first(o,'fouls','personalfouls'))/g);assign(m,'turnoversGame',to/g);assign(m,'turnoversForced',oto/g);assign(m,'offRebounds',orb/g);assign(m,'defRebounds',drb/g);assign(m,'totalReboundPct',ratio(orb+drb,orb+drb+oorb+first(d,'defensiverebounds')));assign(m,'oppOffReboundPct',ratio(oorb,oorb+drb));assign(m,'pointsOffTurnovers',first(o,'pointsoffturnovers')/g);assign(m,'pointsOffTurnoversAllowed',first(d,'pointsoffturnovers')/g);assign(m,'secondChance',first(o,'secondchancepoints')/g);assign(m,'secondChanceAllowed',first(d,'secondchancepoints')/g);assign(m,'pointsPaint',first(o,'pointsinthepaint')/g);assign(m,'paintAllowed',first(d,'pointsinthepaint')/g);assign(m,'fastBreak',first(o,'fastbreakpoints')/g);assign(m,'benchPoints',first(o,'benchpoints')/g);assign(m,'oppAssistRate',ratio(first(d,'assists'),ofgm));diffs.push(m.pointDiff)}
  const mean=diffs.reduce((a,b)=>a+b,0)/(diffs.length||1),sd=Math.sqrt(diffs.reduce((s,x)=>s+(x-mean)**2,0)/(diffs.length||1))||1;
  for(const out of Object.values(output.teams)){const d=out.model.pointDiff??0;out.power=+clamp((d-mean)/sd*5,-18,18).toFixed(1);assign(out.model,'oppAdjusted',out.power)}
  return output;
}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
